github_token: 'tokennn'
members_excluded_from_review:
  - 'Alok2yadav'
  - 'alokyadav2'
  - 'amsaha'
  - 'ankurbhati03'
  - 'apulgupta'
  - 'chloenhy'
  - 'ciscozeusbot'
  - 'ddutta'
  - 'deepshikhagupta'
  - 'dilshad12'
  - 'iskhakov'
  - 'kamaljeet-kaur'
  - 'kanchan963'
  - 'kingmahendra'
  - 'meenakshi-s'
  - 'pkamath'
  - 'Ramaraja'
  - 'ramdootp'
  - 'rohitgithub26'
  - 'sandeep-san'
  - 'satender346'
  - 'shalini-cisco'
  - 'snavien'
  - 'suhailsyed'
  - 'techmng'
  - 'yindolia'
  - 'zeusdownloadbot'
  - 'zeusuibot'
number_of_reviewers: 2
spark_api_key: 'your_spark_key_here'
spark_emails:
  - github_login: "goku"
    spark_email: 'goku@cisco.com'
